<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Mails Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used for mails
    |
    */

    'hello' => 'Hello',
    'alert_notification_from_some1There' => 'Alert Notification from Some1There',
    'alert_generated_for' => 'Alert generated for',
    'unanswered_call' => 'Unanswered call',
    'last_location' => 'Last Location',
    'click_here_to_check_the_map_location_of' => 'Click here to check the map location of',
    'location_based_ervices' => 'Location Based Services',
    'hospitals_near' => 'Hospitals Near',
    'emergency_services_near' => 'Emergency Services Near',
    'emergency_callout' => 'Emergency Callout',
    'type' => 'Type',
    'name' => 'Name',
    'mobile' => 'Mobile',
    'emergency_contacts' => 'Emergency Contacts',
    'thanks' => 'Thanks',
    'all_copyrights_reserved' => 'All copyrights reserved',
    'false_alert_notification' => 'It was a false alert from Some1There. Please ignore the panic notification from',
    'your_passcode_for_some1There_is' => 'Your Passcode for Some1There is',
    'link_update_your_password' => 'Please click on the following link to update your password',
    'reset_password' => 'RESET PASSWORD',
    'sos_alert' => 'SOS Alert from Some1There. Alert generated by',
    'welcome' => 'Welcome to Some1There! Please click on the following link to confirm as a Trusted Contact for',
    'approve' => 'APPROVE',
    'reject' => 'REJECT',
    'alert_for' => 'Alert for',
    'false_alert_from' => 'False alert from',
    'passcode_for' => 'Passcode for',
    'forgot_password_for' => 'Forgot Password for',
    'sos_alert_by' => 'SOS Alert by',
    'confirm_trusted_contact' => 'Confirm Trusted Contact',
    'reset_your_password' => 'Reset your Password',
    'enter_password_details' => 'Enter your new password details',
    'new_password' => 'New Password',
    'confirm_password' => 'Confirm Password',
    'submit_password' => 'Submit to Reset Password',
    'please_find_the_attachment' =>'Please Find The Attachment Below'
];
